/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cb.kitab;

import cb.kitab.utils.Koneksi;
import cb.kitab.utils.ListTableModel;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JRViewer;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author swalayan
 */
public class Kebutuhan extends javax.swing.JFrame {
    ResultSet rs,rsSP;
    Koneksi kn = new Koneksi();
    /**
     * Creates new form Kebutuhan
     */
    public Kebutuhan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTblKeb = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTblKeb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTblKeb);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        ArrayList<String> column = new ArrayList<String>();
            column.add("PID");
            column.add("Deskripsi");
            column.add("Keb. Awal");
            column.add("terbeli");
            column.add("Kebutuhan");
            column.add("Stok");
            column.add("kurang");
            
            
            ListTableModel tbl = new ListTableModel(column);
            tbl.setModelEditable( false );
            
        String sp1,sp2;
        sp1 = "{CALL spHitungKebutuhanKitab(?)}";
        sp2 = "{CALL spHitungTerbeli(?)}";
        
        try {
          rs = kn.stmt.executeQuery("select PID,MatPel,Stok from tb_matpel order by PID");        
          
          ArrayList<List> data = new ArrayList<List>();
		while (rs.next())
		{
                    int keb,beli,stok;
                    keb = hitungSP(rs.getString(1),sp1);
                    beli = hitungSP(rs.getString(1),sp2);
                    stok = rs.getInt(3);
                            
			ArrayList<Object>row = new ArrayList<Object>(7);
			row.add(0, rs.getObject(1));
			row.add(1, rs.getObject(2));
                        row.add(2, keb);
			row.add(3, beli);
                        row.add(4, keb - beli);
                        row.add(5, stok);
                        row.add(6, keb - beli - stok);
                                                
			data.add(row );
		}
                
                tbl.insertRows(0, data);        
        
        jTblKeb.setModel(tbl);
        
        } catch (SQLException ex) {
            Logger.getLogger(Kebutuhan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {                                         
            String path = System.getProperties().getProperty("java.class.path").split(";")[System.getProperties().getProperty("java.class.path").split(";").length - 1] + "/";
            String file = path+"cb/kitab/laporan/report1.jrxml";
            String SQL = "select * from tb_santri";
            ResultSet rs = kn.stmt.executeQuery(SQL);
            
            JasperPrint jasperPrint;
            JRResultSetDataSource jrRS = new JRResultSetDataSource (rs);
            JasperReport jasperReport = JasperCompileManager.compileReport(file);          
            jasperPrint = JasperFillManager.fillReport(jasperReport, null, jrRS);
            JRViewer aViewer = new JRViewer(jasperPrint);
            aViewer.setVisible(true);
            /*
            JDialog viewer = new JDialog();
            viewer.setTitle(".: Jasper Report :.");             
            viewer.setAlwaysOnTop(true);
            viewer.getContentPane().add(aViewer);
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();     
            viewer.setBounds(0,0,screenSize.width, screenSize.height);
            viewer.setVisible(true);
            */            
        } catch (SQLException | JRException ex) {
            Logger.getLogger(Kebutuhan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
private int hitungSP(String PID,String SP) throws SQLException {          
          int hasil = 0;
          CallableStatement cStmt = kn.conn.prepareCall(SP);
          cStmt.setString(1, PID);
          cStmt.execute();
          ResultSet rs1 = cStmt.getResultSet();
          while (rs1.next()) {
              hasil = rs1.getInt(1);
          }
          rs1.close();

          /* process second result set */
          if (cStmt.getMoreResults()) {
               ResultSet rs2 = cStmt.getResultSet();
               while (rs2.next()) {
                    System.out.println(rs2.getInt(1) + " " + rs2.getString(2) + " "
                              + rs2.getString(3));
               }
               rs2.close();
          }
          cStmt.close();
        return hasil;
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kebutuhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kebutuhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kebutuhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kebutuhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kebutuhan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblKeb;
    // End of variables declaration//GEN-END:variables
}
