/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cb.kitab;

import cb.kitab.utils.Koneksi;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import cb.kitab.dialog.JDlgCari;
import cb.kitab.utils.PrintFile;
import cb.kitab.utils.TextUtils;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.DecimalFormat;
import javax.print.PrintException;
import javax.swing.table.TableColumn;


/**
 *
 * @author sanjaya
 */
public class Transaksi extends javax.swing.JFrame {
    private final Koneksi kn = new Koneksi();
    private ResultSet rsTmp,rsExe,rsShow;
    private DecimalFormat numFormat = new DecimalFormat("#,###,###");
    private Integer total,bayar,kembali;
    private String idTrans;

    /**
     * Creates new form Menu
     */
    public Transaksi() {
        KeyboardFocusManager manager = KeyboardFocusManager.getCurrentKeyboardFocusManager();
        manager.addKeyEventDispatcher(new MyDispatcher());

        initComponents();
        setLocationRelativeTo(null);
        bersih();
    }

    private class MyDispatcher implements KeyEventDispatcher {
        @Override
        public boolean dispatchKeyEvent(KeyEvent e) {
            if (e.getID() == KeyEvent.KEY_PRESSED) {
                if (e.getKeyCode() == KeyEvent.VK_F2){
                    cariPelanggan();
                }                                
                if (e.getKeyCode() ==KeyEvent.VK_F3){
                    cariBarang();
                }
                if (e.getKeyCode() ==KeyEvent.VK_F4){
                    cariPaket();
                }
                if (e.getKeyCode() ==KeyEvent.VK_F5){
                    bayar();
                }
                if (e.getKeyCode() ==KeyEvent.VK_F6){
                    hapusBarang();
                }
                if (e.getKeyCode() ==KeyEvent.VK_F7){
                    bersih();
                }
                if (e.getKeyCode() ==KeyEvent.VK_F11){
                    cetakStruk(idTrans);
                }
            } else if (e.getID() == KeyEvent.KEY_RELEASED) {
//                System.out.println("2test2");
            } else if (e.getID() == KeyEvent.KEY_TYPED) {
//                System.out.println("3test3");
            }
            return false;
        }       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTblTrans = new javax.swing.JTable();
        jLbTotal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txBayar = new javax.swing.JTextField();
        jLbBayar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txKembali = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLbid = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLbNama = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLbKamar = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLbKelas = new javax.swing.JLabel();
        txIdBarang = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Transaksi");
        setState(6);

        jTblTrans.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTblTrans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTblTrans.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(jTblTrans);

        jLbTotal.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLbTotal.setForeground(java.awt.Color.red);
        jLbTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLbTotal.setText("Total");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setLabelFor(txBayar);
        jLabel5.setText("Bayar");

        txBayar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txBayar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txBayar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txBayar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txBayarCaretUpdate(evt);
            }
        });
        txBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txBayarActionPerformed(evt);
            }
        });

        jLbBayar.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLbBayar.setForeground(java.awt.Color.green);
        jLbBayar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLbBayar.setText("0");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setLabelFor(txKembali);
        jLabel7.setText("Kembali");

        txKembali.setEditable(false);
        txKembali.setBackground(new java.awt.Color(255, 255, 255));
        txKembali.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txKembali.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txKembali.setText("0");
        txKembali.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txKembali.setEnabled(false);
        txKembali.setFocusable(false);
        txKembali.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txKembaliCaretUpdate(evt);
            }
        });

        jLabel2.setText("| F2 : Cari Pelanggan | F3 : Tambah Barang | F4 : Tambah Paket | F5 : Bayar Transaksi | F6 : Hapus Barang | F7 : Batalkan Transaksi | F11 : Cetak Transaksi");

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("ID   :");

        jLbid.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLbid.setText("ID");

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setLabelFor(jLbNama);
        jLabel3.setText("Nama :");

        jLbNama.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLbNama.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setLabelFor(jLbKamar);
        jLabel4.setText("Kamar:");

        jLbKamar.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLbKamar.setText("Kamar");

        jLabel8.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("Kelas:");

        jLbKelas.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLbKelas.setText("Kelas");
        jLbKelas.setMaximumSize(new java.awt.Dimension(34, 22));
        jLbKelas.setMinimumSize(new java.awt.Dimension(34, 22));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLbid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLbKamar, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLbKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLbNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLbid)
                            .addComponent(jLbNama)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel4)
                        .addComponent(jLbKamar)
                        .addComponent(jLbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        txIdBarang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txIdBarang.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(185, 185, 185)
                                .addComponent(jLbBayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txIdBarang)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txIdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(txKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLbBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txBayarActionPerformed
        if (hitungTotal() == 0) {
            return;            
        }
        
        if (jLbBayar.getForeground()==Color.green){
            total = hitungTotal();
            bayar = tryParseInt(txBayar.getText());
            kembali=  bayar - total;

            if (total > bayar){
                JOptionPane.showMessageDialog(rootPane, "pembayaran tidak cukup...");
                txBayar.selectAll();
                txKembali.setText("0");
                return;
            }

            jLbBayar.setForeground(Color.blue);
            txKembali.setText(numFormat.format(kembali)); 
        } else
        if (jLbBayar.getForeground()==Color.blue){
            simpanData();
        }            

    }//GEN-LAST:event_txBayarActionPerformed

    private void txKembaliCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txKembaliCaretUpdate
            jLbBayar.setText(txKembali.getText());            
    }//GEN-LAST:event_txKembaliCaretUpdate

    int tryParseInt(String value) { 
        try {  
            return Integer.parseInt(value);  
        } catch(NumberFormatException nfe) {  
            return 0;
        }  
}
    private void txBayarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txBayarCaretUpdate
        txKembali.setText("0");
        jLbBayar.setForeground(Color.green);
        
        if (txBayar.getText().equals("")) {
            jLbBayar.setText("0");            
        } else {
            jLbBayar.setText(numFormat.format(tryParseInt(txBayar.getText())));
            //jLbBayar.setText(txBayar.getText());
        }

    }//GEN-LAST:event_txBayarCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLbBayar;
    private javax.swing.JLabel jLbKamar;
    private javax.swing.JLabel jLbKelas;
    private javax.swing.JLabel jLbNama;
    private javax.swing.JLabel jLbTotal;
    private javax.swing.JLabel jLbid;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblTrans;
    private javax.swing.JTextField txBayar;
    private javax.swing.JTextField txIdBarang;
    private javax.swing.JTextField txKembali;
    // End of variables declaration//GEN-END:variables

    
    private Integer hitungTotal() {
        Integer total = 0;
        for (int i = 0; i < jTblTrans.getRowCount(); i++) {
            total += (Integer) jTblTrans.getValueAt(i, 3);
            jTblTrans.setValueAt(i+1, i, 0);
        }
        
        return total;
    }

    private void clearTable() {
        jTblTrans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "PID", "Deskripsi", "Harga","HPP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, 
                java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
            
            public boolean isCellEditable(int rowIndex, int mColIndex) {
                return false;
            }
        });

        int[] columnsWidth = {
                50, 75, 470, 100, 0
        };

        int i = 0;
        for (int width : columnsWidth) {
            TableColumn column = jTblTrans.getColumnModel().getColumn(i++);
            column.setMinWidth(width);
            column.setMaxWidth(width);
            column.setPreferredWidth(width);
        }       
    }

    @SuppressWarnings("empty-statement")
    private String _idTrans() {
        String tgl,hari = "00000000",kd = "";
        Integer tot=0;
        
        try {
            rsTmp = kn.stmt.executeQuery("select count(id_Trans) as tot, date(now()) as sekarang from "+
                    "tb_jual_global where Tanggal = date(now())");
        rsTmp.first();
        
        tgl =rsTmp.getString("sekarang");
        hari = tgl.replace("-", "");
        
        tot = rsTmp.getInt("tot")+1;
        
        
        } catch (SQLException ex) {
            Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (tot<10000)  {kd="";}
        if (tot<1000)   {kd="0";}
        if (tot<100)    {kd="00";}
        if (tot<10)     {kd="000";}
        
        return "TR-"+hari+"-"+kd+Integer.toString(tot);        
    }

    private void simpanData() {
        String _isi = "",_id= _idTrans();
        
        for (int i = 0; i < jTblTrans.getRowCount(); i++) {
            _isi += "('"+_id+"','"+jTblTrans.getValueAt(i, 0)+
                    "','"+jTblTrans.getValueAt(i, 1)+
                    "','"+jTblTrans.getValueAt(i, 4)+
                    "','"+jTblTrans.getValueAt(i, 3)+"'),";
        }
        _isi=_isi.substring(0,_isi.length()-1);
        //System.out.println(_isi);
        
        try {
        //if (kn.conn.getAutoCommit()){kn.conn.setAutoCommit(false);}
        
        kn.conn.setAutoCommit(false);
        
        kn.stmt.executeUpdate("insert into tb_jual_global(id_Trans,Tanggal, "+
                "jam,Pelanggan_id,Total,Bayar,Kembali) values "+
                "('"+_id+"',date(now()),time(now()),'"+jLbid.getText()
                +"','"+total+"','"+bayar+"','"+kembali+"')");
        
        kn.stmt.executeUpdate("insert into tb_jual_rinci(Trans_id,no,barang_id,HPP,Harga) values "+_isi );
        
        
        kn.conn.commit();
        
        JOptionPane.showMessageDialog(rootPane, "Data Berhasil disimpan...");
        this.idTrans = _id;    
        cetakStruk(this.idTrans);
        
        bersih();
         } catch (SQLException ex) {
            Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
                
   }

    private void cetakStruk(String KodeTrans) {
        char ent = '\n';
        String data="",_harga,_total,_bayar,_kembali;
        int lebar = 38;
        
        if ((KodeTrans.equals(""))|| (KodeTrans.equals(null))){
            System.out.println("data kosong....");
            return;
        }
        
        try {
            rsShow = kn.stmt.executeQuery("select * from vw_Jual where id_Trans='"+KodeTrans+"'");
            rsShow.first();
            
            _total = numFormat.format(rsShow.getInt("Total"));
            _bayar = numFormat.format(rsShow.getInt("Bayar"));
            _kembali = numFormat.format(rsShow.getInt("Kembali"));
            
            for (int i = 0; i < lebar; i++) {data+="=";}
            data+= ent;
            
            data+= "kd Trans. : "+rsShow.getString("id_Trans")+ent;
            data+= "Pelanggan : "+rsShow.getString("Nama")+ent;
            data+= "Kelas     : "+rsShow.getString("Kelas")+ent;
            data+= "Tgl/Jam   : "+rsShow.getString("Tanggal")+" "+rsShow.getString("jam")+ent;
            
            for (int i = 0; i < lebar; i++) {data+="-";}
            data+= ent;
            
            do{  
                _harga = numFormat.format(rsShow.getInt("Harga"));
                data+= TextUtils.wrapText(rsShow.getString("no")+" . " + rsShow.getString("Deskripsi"),lebar,4)+ent;
                data+= TextUtils.setText(_harga +" X 1 PCS =  "+_harga, lebar, 2)+ent;
            } while (rsShow.next());
            
            for (int i = 0; i < lebar; i++) {data+="-";}
            data+= ent;
             
            data+= "Total   :";
            data+= TextUtils.setText(_total, lebar-9, 2)+ent;
            data+= "Bayar   :";
            data+= TextUtils.setText(_bayar, lebar-9, 2)+ent;
            data+= "Kembali :";
            data+= TextUtils.setText(_kembali, lebar-9, 2)+ent;
            data+= ent;
            data+= TextUtils.setText("TERIMA KASIH", lebar, 1)+ent+ent+ent+ent;
            
            data+= TextUtils.setText("DUTA SWALAYAN", lebar, 1)+ent;
            data+= TextUtils.setText("Telp. (0343) 613882", lebar, 1)+ent;
            
            TextUtils.SimpankeFile(data, "cetak.prn");
            
            //PrintException | IOException | 
            PrintFile.printTextFile("cetak.prn");
                
        } catch ( PrintException | IOException | SQLException ex) {
                Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    private void bersih() {
        jLbid.setText("");
        jLbNama.setText("");
        jLbKelas.setText("");
        jLbKamar.setText("");

        jLbTotal.setText("Total");

        txBayar.setText("0");
        txBayar.setFocusable(false);
        
        jLbBayar.setText("0");
        
        clearTable();
        jTblTrans.requestFocus();
    }

    private void cariPelanggan() {
        JDlgCari cr = new JDlgCari(this, "select * from tb_pelanggan","Nama");
        cr.setTitle("Cari Pelanggan");
        cr.setVisible(true);
        if (cr.dicari()){
            tampilData(cr.getHasil(0));
        }
    }

    private void tampilData(String id) {        
        try {
            rsTmp = kn.stmt.executeQuery("select * from tb_pelanggan where id ='"+id+"'");
            
            if (rsTmp.last()){
                jLbid.setText(rsTmp.getString("id"));
                jLbNama.setText(rsTmp.getString("Nama"));
                jLbKelas.setText(rsTmp.getString("Kelas"));
                jLbKamar.setText(rsTmp.getString("kamar"));
                jLbBayar.setText("0");
            } else {
                jLbid.setText("");
                jLbNama.setText("");
                jLbKelas.setText("");
                jLbKamar.setText("");

                JOptionPane.showMessageDialog(rootPane, "Data tidak ditemukan", "Not Found", 
                      JOptionPane.ERROR_MESSAGE);

            }

            txIdBarang.setText("");

        } catch (SQLException ex) {
            Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }
        
    private void cariBarang() {
        JDlgCari cr = new JDlgCari(this, "select id,Deskripsi from tb_barang","Deskripsi");
        cr.setTitle("Cari Barang");
        cr.setVisible(true);
        if (cr.dicari()){
            tambahBarang(cr.getHasil(0));
        }
    }
 
    private void tambahBarang(String id) {        
            DefaultTableModel tbl = new DefaultTableModel();
            tbl= (DefaultTableModel) jTblTrans.getModel();
            int no=tbl.getRowCount()+1;
        try {
            rsShow = kn.stmt.executeQuery("select * from tb_barang where id ='"+id+"'");
            while (rsShow.next()){
                tbl.addRow(new Object[]{
                    new Integer(no++),
                    rsShow.getString("id"),
                    rsShow.getString("Deskripsi"),
                    new Integer(rsShow.getInt("Harga")),
                    new Integer(rsShow.getInt("HPP"))
                });
                
                jTblTrans.setModel(tbl);
            }
            ubahBarang();
            
            jLbTotal.setText(numFormat.format(hitungTotal()));        
        } catch (SQLException ex) {
            Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
        
    private void cariPaket() {
        JDlgCari cr = new JDlgCari(this, "select id,Nama_Paket from tb_paket","Nama_Paket");
        cr.setTitle("Cari Paket");
        cr.setVisible(true);
        if (cr.dicari()){
            tambahPaket(cr.getHasil(0));
        }
    }

    private void tambahPaket(String _id) {
            //clearTable();
            DefaultTableModel tbl = new DefaultTableModel();
            tbl= (DefaultTableModel) jTblTrans.getModel();
            int no=1;
            no += tbl.getRowCount();
        try {
            rsShow = kn.stmt.executeQuery("select * from vw_paket where paket_id ='"+_id+"' order by barang_id");
            while (rsShow.next()){
                tbl.addRow(new Object[]{
                    new Integer(no++),
                    rsShow.getString("barang_id"),
                    rsShow.getString("Deskripsi"),
                    new Integer(rsShow.getInt("Harga")),
                    new Integer(rsShow.getInt("HPP"))
                });
                
                jTblTrans.setModel(tbl);
            }
            ubahBarang();
            
            jLbTotal.setText(numFormat.format(hitungTotal()));        
        } catch (SQLException ex) {
            Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void ubahBarang(){
        jTblTrans.requestFocus();
        jTblTrans.changeSelection(jTblTrans.getRowCount()-1,0,false,false);
        txBayar.setText("0");
        txBayar.setFocusable(true);
    }
    
    private void bayar(){
        if (bisaBayar()){
            txBayar.setFocusable(true);
            txBayar.requestFocus();
            txBayar.selectAll();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Data Belum Lengkap", "Data Belum Lengkap", 
                   JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private boolean bisaBayar(){
        boolean hasil=false;
        
        if ((! jLbid.getText().equals(""))&& (jTblTrans.getRowCount()!=0)){
            hasil = true;
        }
        return hasil;
    }
    
    private void hapusBarang(){
        int pilih,jumlahPilih;
        DefaultTableModel tbl = new DefaultTableModel();
        tbl= (DefaultTableModel) jTblTrans.getModel();
        pilih = jTblTrans.getSelectedRow();
        jumlahPilih = jTblTrans.getSelectedRowCount();
        
        if (pilih==-1){
            return;                    
        }
        
        for (int i = 0; i < jumlahPilih; i++) {
            tbl.removeRow(pilih);
        }
        
        if (pilih!=0){
            pilih -=1;
        }
            
        jTblTrans.changeSelection(pilih,0,false,false);
        hitungTotal();
    }
    
}
