/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cb.kitab.dialog;

import cb.kitab.Santri;
import cb.kitab.utils.Koneksi;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author swalayan
 */
public class EditSantri extends javax.swing.JDialog {
    private Koneksi kn = new Koneksi();
    private ResultSet rs;
    private String idPaket;
    private String id="";
    
    /**
     * Creates new form EditSantri
     */
    public EditSantri(java.awt.Frame parent, String id) {
        super(parent, true);
        initComponents();
        setLocationRelativeTo(null);
        this.id =  id;
        loadKelas();
        tampilData(id);
    }
    public EditSantri(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        setLocationRelativeTo(null);
        loadKelas();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txNama = new javax.swing.JTextField();
        cbKelas = new javax.swing.JComboBox();
        txKamar = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel2.setText("Nama");

        jLabel3.setText("Kelas");

        cbKelas.setEditable(true);
        cbKelas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { }));

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jLabel5.setText("Kamar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(363, Short.MAX_VALUE)
                .addComponent(btnSimpan)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbKelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txKamar)
                    .addComponent(txNama))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnSimpan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
       try {
           //generateNIS((String) cbKelas.getSelectedItem(),true);
           if (id.equals("")) {               
            
               kn.stmt.executeUpdate("insert into tb_pelanggan(Nama,Kamar,Kelas) values "+
                       "('"+txNama.getText()+"','"+txKamar.getText()+"','"+
                       cbKelas.getSelectedItem()+"')");
               JOptionPane.showMessageDialog(rootPane, "Data Berhasil disimpan...");

           } else {
            
               kn.stmt.executeUpdate("update tb_pelanggan set Nama= '"+txNama.getText()+
                       "',Kamar='"+txKamar.getText()+"',Kelas='"+cbKelas.getSelectedItem()+
                       "' where id= '"+id+"'");
               
               JOptionPane.showMessageDialog(rootPane, "Data Berhasil diUbah...");

           } 
           this.dispose();
       } catch (SQLException ex) {
             Logger.getLogger(EditSantri.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_btnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditSantri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditSantri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditSantri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditSantri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditSantri dialog = new EditSantri(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox cbKelas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txKamar;
    private javax.swing.JTextField txNama;
    // End of variables declaration//GEN-END:variables

    private void loadKelas() {
         try {
            rs = kn.stmt.executeQuery("select distinct kelas from tb_pelanggan");
            while (rs.next()) {                
                cbKelas.addItem(rs.getObject("kelas"));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Santri.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void tampilData(String id) {
         try {
            rs = kn.stmt.executeQuery("select * from tb_pelanggan where id ='"+id+"'");
            while (rs.next()) {                
                txNama.setText(rs.getString("Nama"));
                txKamar.setText(rs.getString("Kamar"));
                cbKelas.setSelectedItem(rs.getObject("Kelas"));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Santri.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private String generateNIS(String kelas,boolean Baru) {
        String kode = "",kd = "", hasil="";
        int tot = 0;
        try {
            rs = kn.stmt.executeQuery("select * from tbPaketSiswa where kelas ='"+kelas+"'");
            while (rs.next()) {                
                idPaket = rs.getString("idPaket");
                kode    = rs.getString("kode");
            }
            
            if (Baru){           
                rs = kn.stmt.executeQuery("select count(NIS) as total from tb_santri where KelasBaru ='"+kelas+"'");
                while (rs.next()) {                
                    tot = rs.getInt("total")+1;
                }

                if (tot<1000)  {kd="";}
                if (tot<100)   {kd="0";}
                if (tot<10)    {kd="00";}

                hasil= kode+kd+tot;
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Santri.class.getName()).log(Level.SEVERE, null, ex);
        }        
        return hasil;
    }
}
